_BASE_: "../degradation_model.yaml"

DEVICE: "0" # "0" means GPU 0, "0,1" means GPU 0 and 1, etc.
EXP_NAME: "rfdnet_x4-df2k" # Name of the experiment
PHASE: "psnr" # psnr, gan
UPSCALE_FACTOR: 4

DATASET:
  TRAIN_GT_IMAGES_DIR: "datasets/DF2K/DF2K_multiscale_sub_image_384x384"  # 178,574 images
  TRAIN_LR_IMAGES_DIR: ""

  VAL_GT_IMAGES_DIR: "datasets/Set5/X4/GT"
  VAL_LR_IMAGES_DIR: "datasets/Set5/X4/LR"

MODEL:
  G:
    TYPE: "rfdnet_x4"
    IN_CHANNELS: 3
    OUT_CHANNELS: 3
    CHANNELS: 50

TRAIN:
  RESUME_G: ""

  # train weights
  G_WEIGHTS_PATH: ""

  # train datasets
  IMAGE_SIZE: 256
  BATCH_SIZE: 64  # 178,574 / 64 ~= 2,790 iters / epoch
  NUM_WORKERS: 4

  # train solver
  SOLVER:
    G:
      OPTIM:
        TYPE: "adam"
        LR: 0.0005
        BETAS: [ 0.9, 0.999 ]

      LR_SCHEDULER:
        TYPE: "step_lr"
        STEP_SIZE: 72  # epochs / 5
        GAMMA: 0.5

  # loss config
  LOSS:
    PIXEL:
      TYPE: "l1_loss"
      WEIGHT: 1.0

  # train hyper-parameters
  EPOCHS: 359  # 359 * 2790 = 1,001,610 ~= 1,000,000 iters

  # train setup
  LOCAL_RANK: -1
  RANK: -1
  WORLD_SIZE: 1
  DIST_URL: "env://"

  # train results
  OUTPUT_DIR: "results/train"
  VERBOSE: True

EVAL:
  WEIGHTS_PATH: "results/train/rfdnet_x4-df2k/weights/g_last_checkpoint.pkl"
  NIQE_WEIGHTS_PATH: "results/pretrained_models/niqe_model.mat"
  ONLY_TEST_Y_CHANNEL: True