_BASE_: "../degradation_model.yaml"

DEVICE: "0" # "0" means GPU 0, "0,1" means GPU 0 and 1, etc.
EXP_NAME: "realesrnet_x2-df2k" # Name of the experiment
PHASE: "psnr" # psnr, gan
UPSCALE_FACTOR: 2

DATASET:
  TRAIN_GT_IMAGES_DIR: "datasets/DF2K/DF2K_multiscale_sub_image_384x384"  # 178574 images
  TRAIN_LR_IMAGES_DIR: ""

  VAL_GT_IMAGES_DIR: "datasets/Set5/X2/GT"
  VAL_LR_IMAGES_DIR: "datasets/Set5/X2/LR"

MODEL:
  G:
    TYPE: "rrdbnet_x2"
    IN_CHANNELS: 3
    OUT_CHANNELS: 3
    CHANNELS: 64
    GROWTH_CHANNELS: 32
    NUM_RRDB: 23

TRAIN:
  RESUME_G: ""

  # train weights
  G_WEIGHTS_PATH: ""

  # train datasets
  IMAGE_SIZE: 128
  BATCH_SIZE: 16  # 178574 / 16 ~= 11160 iters / epoch
  NUM_WORKERS: 4

  # train solver
  SOLVER:
    G:
      OPTIM:
        TYPE: "adam"
        LR: 0.0002
        BETAS: [ 0.9, 0.99 ]

      LR_SCHEDULER:
        TYPE: "constant"
        FACTOR: 1.0
        TOTAL_ITERS: 90

  # loss config
  LOSS:
    PIXEL:
      TYPE: "l1_loss"
      WEIGHT: 1.0

  # train hyper-parameters
  EPOCHS: 90  # 90 * 11160 = 1,004,400 ~= 1,000,000 iters

  # train setup
  LOCAL_RANK: -1
  RANK: -1
  WORLD_SIZE: 1
  DIST_URL: "env://"

  # train results
  OUTPUT_DIR: "results/train"
  VERBOSE: True

EVAL:
  WEIGHTS_PATH: "results/train/realesrnet_x2-df2k/weights/g_last_checkpoint.pkl"
  NIQE_WEIGHTS_PATH: "results/pretrained_models/niqe_model.mat"
  ONLY_TEST_Y_CHANNEL: True