DEGRADATION_MODEL_PARAMETERS_DICT:
  SINC_KERNEL_SIZE: 21
  GAUSSIAN_KERNEL_RANGE: [ 7, 9, 11, 13, 15, 17, 19, 21 ]
  GAUSSIAN_KERNEL_TYPE: [ "isotropic", "anisotropic","generalized_isotropic", "generalized_anisotropic","plateau_isotropic", "plateau_anisotropic" ]
  # first-order degradation parameters
  GAUSSIAN_KERNEL_PROBABILITY1: [ 0.45, 0.25, 0.12, 0.03, 0.12, 0.03 ]
  SINC_KERNEL_PROBABILITY1: 0.1
  GAUSSIAN_SIGMA_RANGE1: [ 0.2, 3 ]
  GENERALIZED_KERNEL_BETA_RANGE1: [ 0.5, 4 ]
  PLATEAU_KERNEL_BETA_RANGE1: [ 1, 2 ]
  # second-order degradation parameters
  GAUSSIAN_KERNEL_PROBABILITY2: [ 0.45, 0.25, 0.12, 0.03, 0.12, 0.03 ]
  SINC_KERNEL_PROBABILITY2: 0.1
  GAUSSIAN_SIGMA_RANGE2: [ 0.2, 1.5 ]
  GENERALIZED_KERNEL_BETA_RANGE2: [ 0.5, 4 ]
  PLATEAU_KERNEL_BETA_RANGE2: [ 1, 2 ]
  SINC_KERNEL_PROBABILITY3: 0.8

DEGRADATION_PROCESS_PARAMETERS_DICT:
  # the probability of triggering a first-order degenerate operation
  FIRST_BLUR_PROBABILITY: 1.0
  # first-order degenerate operating parameters
  RESIZE_PROBABILITY1: [ 0.2, 0.7, 0.1 ]
  RESIZE_RANGE1: [ 0.15, 1.5 ]
  GRAY_NOISE_PROBABILITY1: 0.4
  GAUSSIAN_NOISE_PROBABILITY1: 0.5
  NOISE_RANGE1: [ 1, 30 ]
  POISSON_SCALE_RANGE1: [ 0.05, 3 ]
  JPEG_RANGE1: [ 30, 95 ]
  # the probability of triggering a second-order degenerate operation
  SECOND_BLUR_PROBABILITY: 0.8
  # second-order degenerate operating parameters
  RESIZE_PROBABILITY2: [ 0.3, 0.4, 0.3 ]
  RESIZE_RANGE2: [ 0.3, 1.2 ]
  GRAY_NOISE_PROBABILITY2: 0.4
  GAUSSIAN_NOISE_PROBABILITY2: 0.5
  NOISE_RANGE2: [ 1, 25 ]
  POISSON_SCALE_RANGE2: [ 0.05, 2.5 ]
  JPEG_RANGE2: [ 30, 95 ]