DEVICE: "0"
UPSCALE_FACTOR: 4
WINDOW_WIDTH: 256
WINDOW_HEIGHT: 256
OVERLAP_WIDTH: 32
OVERLAP_HEIGHT: 32
WEIGHTS_PATH: "results/pretrained_models/realesrgan_x4-df2k_degradation.pkl"
INPUTS: "demo/data"
OUTPUT: "demo/output"